services:
  db:
    image: postgres:15-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: wow-auction-db
      POSTGRES_USER: user